import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Instantiable } from '@ctypes/breeze-type-customization';
import {
    cfgApiAddress,
    cfgFeatureSpAppSite,
    MxmAppName,
    MxmAssignedModels
} from 'app/app-config.service';
import {
    AutoGeneratedKeyType,
    DataService,
    EntityAction,
    EntityManager,
    EntityType
} from 'breeze-client';
import { init } from 'rollbar';
import { BehaviorSubject, Observable, Subject } from 'rxjs';
import { filter } from 'rxjs/operators';
import { ISpEntityType, MetadataBase, SpEntityBase } from '../models';
import { CustomMetadataHelperService } from '../service-adapter/custom-metadata-helper';
import { CustomNameConventionService } from '../service-adapter/custom-namingConventionDict';
import { CoreEmProviderService } from './core-em-provider.service';

export interface IEntityChangedEvent {
    entityAction: EntityAction;
    entity: SpEntityBase;
    args: object;
}
export class BaseEmProviderService {
    private featureAppSiteName: string;
    entityManager: EntityManager;
    private dataService: DataService;
    onSaveInProgressChange: BehaviorSubject<boolean>;
    onEntityManagerChange: Subject<IEntityChangedEvent>;

    constructor(
        private http: HttpClient,
        private metaHelper: CustomMetadataHelperService,
        private nameConv: CustomNameConventionService,
        private emProviderService: CoreEmProviderService,
        appSiteName: string,
        private featureNameSpace: string,
        private appName: MxmAppName,
        private appEntities: Array<
            Instantiable<MetadataBase<SpEntityBase>>
        > = []
    ) {
        this.featureAppSiteName = appSiteName;
        this.onSaveInProgressChange = new BehaviorSubject(false);
        this.onEntityManagerChange = new Subject();
        this.init();
    }

    init(): void {
        this.dataService = new DataService({
            serviceName: cfgApiAddress(this.featureAppSiteName),
            hasServerMetadata: false,
            adapterName: 'SpODataService'
        });

        this.dataService.odataServiceEndpoint = cfgFeatureSpAppSite(
            this.featureAppSiteName
        );

        this.metaHelper.defaultNamespace = this.featureNameSpace;
        this.metaHelper.defaultAutoGenKeyType = AutoGeneratedKeyType.Identity;
        const clientToServerNameDictionary = {};

        const appModels = MxmAssignedModels.get(this.appName);

        appModels.forEach(f => console.log(f));
        // this.appEntities.forEach(entity => {
        //     const e = new entity();
        //     e.entityDefinition.createNamingDictionary(
        //         clientToServerNameDictionary,
        //         this.featureNameSpace
        //     );
        // });

        this.nameConv.updateDictionary(clientToServerNameDictionary);

        this.entityManager = new EntityManager({
            dataService: this.dataService,
            metadataStore: this.emProviderService.metadataStore
        });

        this.entityManager.entityChanged.subscribe(changedArgs =>
            this.onEntityManagerChange.next(changedArgs)
        );

        // this.appEntities.forEach(entityMetadata => {
        //     const meta = new entityMetadata();
        //     const type = this.metaHelper.addTypeToStore(
        //         this.emProviderService.metadataStore,
        //         meta.entityDefinition as any
        //     ) as EntityType;
        //     this.emProviderService.metadataStore.registerEntityTypeCtor(
        //         type.shortName,
        //         meta.metadataFor,
        //         meta.initializer
        //     );
        //     meta.addDefaultSelect(type as ISpEntityType);
        //     meta.transformValidators(type as ISpEntityType);
        // });

        this.getRequestDigest();
    }

    filterAttached(
        changedArgs: Observable<IEntityChangedEvent>
    ): Observable<IEntityChangedEvent> {
        return changedArgs.pipe(
            filter(
                changedArg => changedArg.entityAction === EntityAction.Attach
            )
        );
    }

    filterDeleted(
        changedArgs: Observable<IEntityChangedEvent>
    ): Observable<IEntityChangedEvent> {
        return changedArgs.pipe(
            filter(
                changedArg =>
                    changedArg.entity.entityAspect.entityState.isDeleted() &&
                    changedArg.entityAction === EntityAction.EntityStateChange
            )
        );
    }

    getRequestDigest(): void {
        // tslint:disable-next-line: no-this-assignment
        const that = this;
        const headers = new HttpHeaders({
            'Content-Type': 'application/json;odata=verbose',
            Accept: 'application/json;odata=verbose'
        });
        this.http
            .post(
                `${cfgApiAddress(this.featureAppSiteName)}contextinfo`,
                {},
                { headers }
            )
            .subscribe(response => {
                const digest =
                    response['d']['GetContextWebInformation'][
                        'FormDigestValue'
                    ];
                let timeout =
                    response['d']['GetContextWebInformation'][
                        'FormDigestTimeoutSeconds'
                    ];
                if (timeout) {
                    timeout *= 1000;
                    setTimeout(() => {
                        this.getRequestDigest();
                    }, timeout);
                }
                that.entityManager.dataService.requestDigest = digest;
            });
    }

    async saveAllChanges(): Promise<void> {
        try {
            this.onSaveInProgressChange.next(true);
            const results = await this.entityManager.saveChanges();
        } catch (e) {
            console.error(`Saving changes failed ==> ${e}`);
            Promise.reject();
        } finally {
            this.onSaveInProgressChange.next(false);
        }
    }
}
