import { Injectable } from '@angular/core';
import { RegistrationHelper, AagtAppConfig } from '../entities';
import * as breeze from 'breeze-client';
import 'breeze-client-labs/breeze.labs.dataservice.abstractrest';
import 'breeze-client-labs/breeze.labs.dataservice.sharepoint';

@Injectable({
  providedIn: 'root'
})
export class EmProviderService {
  activate = false;
  coreEntityManager: breeze.EntityManager;

  constructor(
    private _regHelper: RegistrationHelper,
    private _aagtConfig: AagtAppConfig,
  ) {
    this.init();
  }

  init(): void {
    const dataAdapter = breeze.config.initializeAdapterInstance('dataService', 'SharePointOData', true) as any;
    dataAdapter.getRequestDigest = () => this._aagtConfig.rawRequestDigest;

    const dataService = new breeze.DataService({
      serviceName: `${this._aagtConfig.appWebUrl}/_api/web/`,
      hasServerMetadata: false
    });

    this.coreEntityManager = new breeze.EntityManager({ dataService: dataService });
    const metaHelper = new breeze.config.MetadataHelper('SP.Squad.Mgr', breeze.AutoGeneratedKeyType.Identity);

    this._regHelper.register(this.coreEntityManager.metadataStore, metaHelper);

  }
}
