import { Injectable } from '@angular/core';
import * as breeze from 'breeze-client';
import * as eb from '../models/_entity-base';
import { EmProviderConfig } from './em-provider-config';
import { SpRepoService } from './sp-repo.service';
import { SpDataserviceAdapter } from './sp-dataservice-adapter';

@Injectable({ providedIn: 'root' })
export class EmProviderService {
    activate = false;
    entityManager: breeze.EntityManager;
    servicePoint: string;

    constructor(private spRooData: SpRepoService,
        private config: EmProviderConfig,
        private spDataserviceAdapter: SpDataserviceAdapter) {
        this.init();
    }

    protected init(): void {
// @ts-ignore
        const dataAdapter = breeze.config.initializeAdapterInstance('dataService', 'SpCustomOData', true) as any;

        dataAdapter.getRequestDigest = () => this.spRooData.getRequestDigest();

        const clientToServerNameDictionary = {
            'SpConfigData:#SP.Data.Aagt': { configKey: 'Title' }
        };
        const nc = breeze.NamingConvention as any;
        const convention = new nc.NamingConventionWithDictionary(
            'spNameConv', breeze.NamingConvention.camelCase, clientToServerNameDictionary);

        convention.setAsDefault();

        const dataService = new breeze.DataService({
            serviceName: `${this.spRooData.appSite}${this.config.serviceEndpoint}/_api/web`,
            hasServerMetadata: false
        });
        this.servicePoint = dataService.serviceName;
        this.entityManager = new breeze.EntityManager({ dataService });
        // @ts-ignore
        const metaHelper = new breeze.config.MetadataHelper(this.config.nameSpace, breeze.AutoGeneratedKeyType.Identity);

        const store = this.entityManager.metadataStore;

        this.config.entities.forEach(entity => {
            const e = new entity() as eb.MetadataBase<eb.SpEntityBase>;
            const type = metaHelper.addTypeToStore(store,
                e.entityDefinition as any) as breeze.EntityType;
            store.registerEntityTypeCtor(type.shortName,
                e.metadataFor, e.initializer);
            e.addDefaultSelect(type);
        });
    }
}
